# MOTORS PART. WheelBase
# GPIO pins in raspberry pi, used to control 2 or 4 motors. 
# To control one motor (or 2 motors in one direction) you will need 3 pins 
# This program is for l298n motor driver. 
motor_enabler_left: 13
motor_in1_left: 19
motor_in2_left: 26
motor_enabler_right: 16
motor_in3_right: 21
motor_in4_right: 20
motors_speed: 0.3 # initial speed of motors (0-1)
# =================================================

# STEPPER MOTOR part. crusher lifting gear
# This settings are for 28BYJ-48 5v stepper motor
stepper_revolution_steps: 2038
stepper_microsteps_in_one_step: 8
stepper_enable_pin: 22
stepper_step_pin: 17
stepper_direction_pin: 27
stepper_speed: 0.0003 #it's a sleep duaration between half step. More duaration - less speed
# =================================================

# Distance ultrasound sensor
# Uses 2 GPIOs for trigger and echo
distance_trigger: 6
distance_echo: 5
# ==================================================

# LCD Text Screen I2C LCM1602
# text_lcd_i2c = x027 